"use strict";
const content=document.querySelector('#content');
const initialTasks=[{id:1,text:'Revisar o protótipo de exemplo',done:false},{id:2,text:'Estudar funções em Python por 25 minutos',done:false},{id:3,text:'Organizar as notas da semana',done:true}];
const initialNotes=[{title:'Projeto de exemplo',body:'Objetivo: criar uma demonstração simples, acessível e fácil de testar. Próximo passo: revisar o formulário.'},{title:'Plano de estudo',body:'Estudar funções, escrever um pequeno exercício e registrar dúvidas. Conteúdo inteiramente fictício.'}];
let tasks=structuredClone(initialTasks),notes=structuredClone(initialNotes),view='chat',messages=[];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function announce(s){document.querySelector('#status').textContent=s;}
function respond(text){const q=text.toLocaleLowerCase('pt-BR');if(/agenda|tarefa|dia/.test(q)){const pending=tasks.filter(t=>!t.done);return pending.length?'Na agenda desta demonstração:\n'+pending.map(t=>'• '+t.text).join('\n')+'\nVocê pode concluir ou adicionar tarefas na aba Agenda.':'Todas as tarefas desta demonstração foram concluídas.';}if(/nota|projeto|resum/.test(q))return notes.length?'Notas disponíveis nesta página:\n'+notes.map(n=>'• '+n.title+': '+n.body).join('\n'):'Não há notas nesta demonstração. Adicione uma na aba Notas.';if(/estud|python/.test(q))return 'Sugestão programada de estudo:\n1. Leia sobre uma função.\n2. Escreva um exercício pequeno.\n3. Teste entradas diferentes.\n\nEsta resposta é um exemplo fixo, não uma geração de IA.';return 'Esta é uma conversa simulada, sem modelo de IA conectado. Posso mostrar as tarefas da agenda, consultar as notas ou apresentar um plano de estudo. Experimente “Como está minha agenda?”.';}
function render(){document.querySelectorAll('[data-view]').forEach(b=>{if(b.dataset.view===view)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});if(view==='chat'){content.innerHTML='<span class="eyebrow">UM LUGAR PARA ORGANIZAR IDEIAS</span><h1>O que vamos organizar?</h1><p>Conversa, tarefas e notas no mesmo espaço.</p><div class="suggestions"><button data-prompt="Como está minha agenda?">Consultar agenda ↗</button><button data-prompt="Resumir minhas notas">Consultar notas ↗</button><button data-prompt="Quero estudar Python">Plano de estudo ↗</button></div><div class="messages" role="log" aria-label="Conversa simulada">'+messages.map(m=>'<div class="message '+(m.user?'user':'')+'"><small>'+(m.user?'VOCÊ':'RESPOSTA SIMULADA')+'</small>'+esc(m.text)+'</div>').join('')+'</div><form id="chat-form" class="composer"><input name="message" aria-label="Mensagem" placeholder="Pergunte sobre agenda, notas ou estudos…" maxlength="500" required><button class="primary">Enviar</button></form><p class="hint">Não informe dados reais. Não há IA, envio de mensagens ou execução de ações externas.</p>';}
else if(view==='agenda'){content.innerHTML='<span class="eyebrow">PASSO A PASSO</span><h1>Agenda de exemplo</h1><p>'+tasks.filter(t=>t.done).length+' de '+tasks.length+' tarefas concluídas nesta sessão.</p><div class="card">'+(tasks.length?tasks.map(t=>'<div class="task '+(t.done?'done':'')+'"><input id="task-'+t.id+'" type="checkbox" data-task="'+t.id+'" '+(t.done?'checked':'')+'><label for="task-'+t.id+'">'+esc(t.text)+'</label><button data-delete-task="'+t.id+'" aria-label="Excluir tarefa: '+esc(t.text)+'">Excluir</button></div>').join(''):'<p class="empty">Nenhuma tarefa. Adicione um exemplo abaixo.</p>')+'</div><form class="add-form" id="task-form"><label>Nova tarefa fictícia<input name="task" maxlength="140" required placeholder="Ex.: revisar uma tela"></label><button class="primary">Adicionar tarefa</button></form>';}
else{content.innerHTML='<span class="eyebrow">CONTEXTO AO SEU ALCANCE</span><h1>Notas de exemplo</h1><p>Conteúdo local que também pode ser consultado na conversa simulada.</p><div class="cards">'+(notes.length?notes.map((n,i)=>'<article class="card"><h2>'+esc(n.title)+'</h2><p>'+esc(n.body)+'</p><button data-delete-note="'+i+'" aria-label="Excluir nota: '+esc(n.title)+'">Excluir nota</button></article>').join(''):'<p class="empty">Nenhuma nota cadastrada.</p>')+'</div><form class="add-form" id="note-form"><label>Título fictício<input name="title" required maxlength="80"></label><label>Conteúdo fictício<textarea name="body" required maxlength="500" rows="3"></textarea></label><button class="primary">Adicionar nota</button></form>';}}
function send(text){if(!text.trim())return;messages.push({user:true,text:text.trim()},{user:false,text:respond(text)});render();announce('Resposta simulada exibida.');document.querySelector('[name="message"]').focus();const log=document.querySelector('.messages');log.scrollTop=log.scrollHeight;}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.view){view=b.dataset.view;render();announce('');}if(b.dataset.prompt)send(b.dataset.prompt);if(b.dataset.deleteTask){tasks=tasks.filter(t=>t.id!==Number(b.dataset.deleteTask));render();announce('Tarefa removida da demonstração.');}if(b.dataset.deleteNote!==undefined){notes.splice(Number(b.dataset.deleteNote),1);render();announce('Nota removida da demonstração.');}if(b.id==='reset'){tasks=structuredClone(initialTasks);notes=structuredClone(initialNotes);messages=[];render();announce('Demonstração restaurada.');}});
document.addEventListener('change',e=>{if(e.target.dataset.task){const t=tasks.find(t=>t.id===Number(e.target.dataset.task));t.done=e.target.checked;const id=t.id;render();document.querySelector('#task-'+id).focus();announce(t.done?'Tarefa concluída.':'Tarefa reaberta.');}});
document.addEventListener('submit',e=>{e.preventDefault();const data=new FormData(e.target);if(e.target.id==='chat-form')send(String(data.get('message')));if(e.target.id==='task-form'){const text=String(data.get('task')).trim();if(!text){announce('Digite uma tarefa.');return;}tasks.push({id:Math.max(0,...tasks.map(t=>t.id))+1,text,done:false});render();announce('Tarefa fictícia adicionada.');}if(e.target.id==='note-form'){const title=String(data.get('title')).trim(),body=String(data.get('body')).trim();if(!title||!body){announce('Preencha título e conteúdo.');return;}notes.push({title,body});render();announce('Nota fictícia adicionada.');}});
render();
